name: Build

on:
  pull_request:
    branches:
      - master
  push:
  release:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - mips_24kc
          - mips_mips32

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare package
        run: |
          sed -i '/^SRCDIR/ s/$/\/feed/' openwrt/Makefile
          mkdir -p feed/scutclient
          mv openwrt/Makefile feed/scutclient/
          cat feed/scutclient/Makefile

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          NO_DEFAULT_FEEDS: 1
          PACKAGES: scutclient

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-packages
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
